const GITHUB_AUTH_TOKEN = "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"
const BOT_NUMBER = "94724865987"
const SESSION_ID = "PRABATH-MD~zXBHGAIY#28TQsRLcZUBDU1P8yD-66GzaePKLOeqgzdk3vnFOFBs"


module.exports = {
GITHUB_AUTH_TOKEN,
BOT_NUMBER,
SESSION_ID
}
